# Generated by Django 3.1.2 on 2023-06-11 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
