# Generated by Django 3.1.2 on 2023-06-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20230611_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='user',
        ),
    ]
