# Generated by Django 3.1.2 on 2023-06-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20230611_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='usuario',
            new_name='user',
        ),
    ]
