# Generated by Django 3.1.2 on 2023-06-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20230619_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='seguimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tiposeguimiento'),
        ),
    ]
