# Generated by Django 3.1.2 on 2023-06-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_lineapedido_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='seguimiento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='seguimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tiposeguimiento'),
        ),
    ]
